### ISSUE TITLE
iOS Implementation required!

### ISSUE THREAD

**Issue by divshekhar** [DevsOnFlutter/reflex#1]
* Listen to all notifications from iOS and send a stream to the flutter side.
* Functions to check notification listening permission and request permission.
* Reply to chat notifications

**Comment by Unevenn** [comment]
@divshekhar As the operating system security on the iOS side, it is not possible for this plugin to work on the iOS side. Close the issue.

**Comment by divshekhar** [comment]
Hi @Unevenn,
Appreciated! Thank you for your suggestion.
