### ISSUE TITLE
Impossible to change the AutoReply message

### ISSUE THREAD

**Issue by alexph01** [DevsOnFlutter/reflex#4]
The `autoReply` field in the `Reflex` class is final. And there seems to be no way to change the reply message depending on the received message. Or maybe I'm overlooking a field or funtion to change the message content?
It would be nice to have a dynamic reply option. For example:
Message received: "hi", auto reply: "hello", later message received: "bye", auto reply: "see ya"

**Comment by divshekhar** [comment]
Hello @alexph01 ,
Thank you for raising an issue. It will be solved soon.
