### ISSUE TITLE
AutoReply only to specific messages

### ISSUE THREAD

**Issue by alexph01** [DevsOnFlutter/reflex#6]
It would be nice if the AutoReply feature would only trigger on specific messages. If someone starts a conversation with "Hello [...]", it would automatically reply to the person, but not otherwise. That way that person would not receive a message every time he/she writes something.

**Comment by divshekhar** [comment]
Hey @alexph01, Thanks for opening an issue. The suggested feature will be added in the upcoming version.

**Comment by RajSarvaiya** [comment]
how can i send dynamic autoreply ?

**Comment by codetinker** [comment]
@divshekhar It's almost a year now =)
By any chance when autoreply on specific message can be implemented?
Autoreply to all messages is not very useful =(

**Comment by divshekhar** [comment]
Hey @codetinker ,
Reflex is a library that allows the user to reply from the notification. It is user's responsibility to automate for specific messages. Hope it helps. Closing this issue, reopen if you have some suggestions.
